# Generated by Django 4.2.28 on 2026-02-21 09:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ai_model', models.CharField(default='CodeT5', max_length=50)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_reports', to='repository.repository')),
            ],
        ),
        migrations.CreateModel(
            name='CodeSmell',
            fields=[
                ('smell_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('smell_type', models.CharField(max_length=100)),
                ('severity_level', models.CharField(max_length=50)),
                ('file_path', models.CharField(max_length=500)),
                ('line_range', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_smells', to='analysis.analysisreport')),
            ],
        ),
    ]
