# Generated by Django 6.0.2 on 2026-05-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisreport',
            name='ai_model',
            field=models.CharField(default='', max_length=100),
        ),
    ]
