# Generated by Django 6.0.2 on 2026-05-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_alter_analysisreport_ai_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesmell',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
