# Generated by Django 4.2.28 on 2026-02-21 09:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefactoringSuggestion',
            fields=[
                ('suggestion_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('suggestion_text', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('smell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='analysis.codesmell')),
            ],
        ),
    ]
